### ISSUE TITLE
Fail build on centos 6.5(64bits)

### ISSUE THREAD

**Issue by zhaozg** [Lua-cURL/Lua-cURLv3#8]
# curl --version

curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

```
gcc -O2 -fPIC -I/usr/local/include/luajit-2.0 -c src/l52util.c -o src/l52util.o -I/usr/include
gcc -O2 -fPIC -I/usr/local/include/luajit-2.0 -c src/lceasy.c -o src/lceasy.o -I/usr/include
In file included from src/lceasy.c:230:
src/lcopteasy.h: In function 'lcurl_easy_set_WILDCARDMATCH':
src/lcopteasy.h:33: error: 'CURLOPT_WILDCARDMATCH' undeclared (first use in this function)
src/lcopteasy.h:33: error: (Each undeclared identifier is reported only once
src/lcopteasy.h:33: error: for each function it appears in.)
src/lcopteasy.h: In function 'lcurl_easy_set_TLSAUTH_USERNAME':
src/lcopteasy.h:77: error: 'CURLOPT_TLSAUTH_USERNAME' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_TLSAUTH_PASSWORD':
src/lcopteasy.h:78: error: 'CURLOPT_TLSAUTH_PASSWORD' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_TLSAUTH_TYPE':
src/lcopteasy.h:79: error: 'CURLOPT_TLSAUTH_TYPE' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_ACCEPT_ENCODING':
src/lcopteasy.h:89: error: 'CURLOPT_ACCEPT_ENCODING' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_TRANSFER_ENCODING':
src/lcopteasy.h:90: error: 'CURLOPT_TRANSFER_ENCODING' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_MAIL_FROM':
src/lcopteasy.h:121: error: 'CURLOPT_MAIL_FROM' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_MAIL_RCPT':
src/lcopteasy.h:122: error: 'CURLOPT_MAIL_RCPT' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_FTP_USE_PRET':
src/lcopteasy.h:137: error: 'CURLOPT_FTP_USE_PRET' undeclared (first use in this function)
src/lcopteasy.h: In function 'lcurl_easy_set_RESOLVE':
src/lcopteasy.h:178: error: 'CURLOPT_RESOLVE' undeclared (first use in this function)
In file included from src/lceasy.c:364:
src/lcinfoeasy.h: In function 'lcurl_easy_get_PRIMARY_PORT':
src/lcinfoeasy.h:30: error: 'CURLINFO_PRIMARY_PORT' undeclared (first use in this function)
src/lcinfoeasy.h: In function 'lcurl_easy_get_LOCAL_IP':
src/lcinfoeasy.h:31: error: 'CURLINFO_LOCAL_IP' undeclared (first use in this function)
src/lcinfoeasy.h: In function 'lcurl_easy_get_LOCAL_PORT':
src/lcinfoeasy.h:32: error: 'CURLINFO_LOCAL_PORT' undeclared (first use in this function)
src/lcinfoeasy.h: In function 'lcurl_easy_get_RTSP_SESSION_ID':
src/lcinfoeasy.h:37: error: 'CURLINFO_RTSP_SESSION_ID' undeclared (first use in this function)
src/lcinfoeasy.h: In function 'lcurl_easy_get_RTSP_CLIENT_CSEQ':
src/lcinfoeasy.h:38: error: 'CURLINFO_RTSP_CLIENT_CSEQ' undeclared (first use in this function)
src/lcinfoeasy.h: In function 'lcurl_easy_get_RTSP_SERVER_CSEQ':
src/lcinfoeasy.h:39: error: 'CURLINFO_RTSP_SERVER_CSEQ' undeclared (first use in this function)
src/lcinfoeasy.h: In function 'lcurl_easy_get_RTSP_CSEQ_RECV':
src/lcinfoeasy.h:40: error: 'CURLINFO_RTSP_CSEQ_RECV' undeclared (first use in this function)
src/lceasy.c: In function 'lcurl_read_callback':
src/lceasy.c:509: warning: incompatible implicit declaration of built-in function 'memcpy'
src/lceasy.c:513: warning: incompatible implicit declaration of built-in function 'memcpy'
src/lceasy.c:541: warning: incompatible implicit declaration of built-in function 'memcpy'
In file included from src/lceasy.c:649:
src/lcopteasy.h: In function 'lcurl_easy_setopt':
src/lcopteasy.h:33: error: 'CURLOPT_WILDCARDMATCH' undeclared (first use in this function)
src/lcopteasy.h:77: error: 'CURLOPT_TLSAUTH_USERNAME' undeclared (first use in this function)
src/lcopteasy.h:78: error: 'CURLOPT_TLSAUTH_PASSWORD' undeclared (first use in this function)
src/lcopteasy.h:79: error: 'CURLOPT_TLSAUTH_TYPE' undeclared (first use in this function)
src/lcopteasy.h:89: error: 'CURLOPT_ACCEPT_ENCODING' undeclared (first use in this function)
src/lcopteasy.h:90: error: 'CURLOPT_TRANSFER_ENCODING' undeclared (first use in this function)
src/lcopteasy.h:121: error: 'CURLOPT_MAIL_FROM' undeclared (first use in this function)
src/lcopteasy.h:122: error: 'CURLOPT_MAIL_RCPT' undeclared (first use in this function)
src/lcopteasy.h:137: error: 'CURLOPT_FTP_USE_PRET' undeclared (first use in this function)
src/lcopteasy.h:178: error: 'CURLOPT_RESOLVE' undeclared (first use in this function)
src/lceasy.c:660: error: 'CURLE_UNKNOWN_OPTION' undeclared (first use in this function)
In file included from src/lceasy.c:670:
src/lcinfoeasy.h: In function 'lcurl_easy_getinfo':
src/lcinfoeasy.h:30: error: 'CURLINFO_PRIMARY_PORT' undeclared (first use in this function)
src/lcinfoeasy.h:31: error: 'CURLINFO_LOCAL_IP' undeclared (first use in this function)
src/lcinfoeasy.h:32: error: 'CURLINFO_LOCAL_PORT' undeclared (first use in this function)
src/lcinfoeasy.h:37: error: 'CURLINFO_RTSP_SESSION_ID' undeclared (first use in this function)
src/lcinfoeasy.h:38: error: 'CURLINFO_RTSP_CLIENT_CSEQ' undeclared (first use in this function)
src/lcinfoeasy.h:39: error: 'CURLINFO_RTSP_SERVER_CSEQ' undeclared (first use in this function)
src/lcinfoeasy.h:40: error: 'CURLINFO_RTSP_CSEQ_RECV' undeclared (first use in this function)
src/lceasy.c:674: error: 'CURLE_UNKNOWN_OPTION' undeclared (first use in this function)
In file included from src/lceasy.c:712:
src/lcopteasy.h: At top level:
src/lcopteasy.h:33: error: 'CURLOPT_WILDCARDMATCH' undeclared here (not in a function)
src/lcopteasy.h:77: error: 'CURLOPT_TLSAUTH_USERNAME' undeclared here (not in a function)
src/lcopteasy.h:78: error: 'CURLOPT_TLSAUTH_PASSWORD' undeclared here (not in a function)
src/lcopteasy.h:79: error: 'CURLOPT_TLSAUTH_TYPE' undeclared here (not in a function)
src/lcopteasy.h:89: error: 'CURLOPT_ACCEPT_ENCODING' undeclared here (not in a function)
src/lcopteasy.h:90: error: 'CURLOPT_TRANSFER_ENCODING' undeclared here (not in a function)
src/lcopteasy.h:121: error: 'CURLOPT_MAIL_FROM' undeclared here (not in a function)
src/lcopteasy.h:122: error: 'CURLOPT_MAIL_RCPT' undeclared here (not in a function)
src/lcopteasy.h:137: error: 'CURLOPT_FTP_USE_PRET' undeclared here (not in a function)
src/lcopteasy.h:178: error: 'CURLOPT_RESOLVE' undeclared here (not in a function)
In file included from src/lceasy.c:724:
src/lcinfoeasy.h:30: error: 'CURLINFO_PRIMARY_PORT' undeclared here (not in a function)
src/lcinfoeasy.h:31: error: 'CURLINFO_LOCAL_IP' undeclared here (not in a function)
src/lcinfoeasy.h:32: error: 'CURLINFO_LOCAL_PORT' undeclared here (not in a function)
src/lcinfoeasy.h:37: error: 'CURLINFO_RTSP_SESSION_ID' undeclared here (not in a function)
src/lcinfoeasy.h:38: error: 'CURLINFO_RTSP_CLIENT_CSEQ' undeclared here (not in a function)
src/lcinfoeasy.h:39: error: 'CURLINFO_RTSP_SERVER_CSEQ' undeclared here (not in a function)
src/lcinfoeasy.h:40: error: 'CURLINFO_RTSP_CSEQ_RECV' undeclared here (not in a function)
```
