### PR TITLE
Fix build with curl 7.62.0

### LINKED ISSUE #134: Unable to compile lcerror.c
gcc -O2 -fPIC -I/home/kyson/workspace/devlop/release/sdk/ar71xx/staging_dir/hostpkg/include -c src/lcerror.c -o src/lcerror.o -I/mnt/sda1/install/lua-5.1.5/src
src/lcerr_easy.h: In function 'lcurl_err_easy_mnemo':
src/lcerror.c:32:22: error: duplicate case value
 #define ERR_ENTRY(E) case CURLE_##E: return #E;
                      ^
src/lcerr_easy.h:74:1: note: in expansion of macro 'ERR_ENTRY'
 ERR_ENTRY ( SSL_CACERT               )
 ^
src/lcerror.c:32:22: error: previously used here
 #define ERR_ENTRY(E) case CURLE_##E: return #E;
                      ^
src/lcerr_easy.h:65:1: note: in expansion of macro 'ERR_ENTRY'
 ERR_ENTRY ( PEER_FAILED_VERIFICATION )
 ^

Please can someone help?

### PR DESCRIPTION
**Pull request by baruchsiach**
Fixes #134.

curl 7.62.0 deprecates the CURLE_SSL_CACERT error code, and unifies it
with CURLE_PEER_FAILED_VERIFICATION. Adjust the errors list to match.

This fixes the following build failure:

src/lcerr_easy.h: In function 'lcurl_err_easy_mnemo':
src/lcerror.c:32:22: error: duplicate case value
 #define ERR_ENTRY(E) case CURLE_##E: return #E;
                      ^
src/lcerr_easy.h:74:1: note: in expansion of macro 'ERR_ENTRY'
 ERR_ENTRY ( SSL_CACERT               )
 ^~~~~~~~~
src/lcerror.c:32:22: note: previously used here
 #define ERR_ENTRY(E) case CURLE_##E: return #E;
                      ^
src/lcerr_easy.h:65:1: note: in expansion of macro 'ERR_ENTRY'
 ERR_ENTRY ( PEER_FAILED_VERIFICATION )
 ^~~~~~~~~

### CODE REVIEW

**Comment by moteus** [comment]
Please check out master branch.
