### ISSUE TITLE
Does not build on Ubuntu Linux 10.04LTS

### ISSUE THREAD

**Issue by stepelu** [Lua-cURL/Lua-cURLv3#58]
I cannot manage to build it on Ubuntu 10.04LTS via Luarock (but I suspect it is not a Luarock issue).

It this version of libcurl unsupported?

```
sp@ubuntu1040lts:~/luarocks/bin$ ./luarocks install lua-curl
Installing https://rocks.moonscript.org/lua-curl-0.3.1-1.src.rock...
Using https://rocks.moonscript.org/lua-curl-0.3.1-1.src.rock... switching to 'build' mode
Archive:  v0.3.1.zip
40695b42648253f2e0b7466256ac292ec37c4602
...
gcc -O2 -fPIC -I/home/sp/luajit/include/lua5.1 -c src/l52util.c -o src/l52util.o -I/usr/include
gcc -O2 -fPIC -I/home/sp/luajit/include/lua5.1 -c src/lceasy.c -o src/lceasy.o -I/usr/include
gcc -O2 -fPIC -I/home/sp/luajit/include/lua5.1 -c src/lcerror.c -o src/lcerror.o -I/usr/include
gcc -O2 -fPIC -I/home/sp/luajit/include/lua5.1 -c src/lchttppost.c -o src/lchttppost.o -I/usr/include
gcc -O2 -fPIC -I/home/sp/luajit/include/lua5.1 -c src/lcurl.c -o src/lcurl.o -I/usr/include
src/lcurl.c:173:28: error: ‘CURLGSSAPI_DELEGATION_NONE’ undeclared here (not in a function)
 #define FLG_ENTRY(N) { #N, CURL##N },
                            ^
src/lcflags.h:48:1: note: in expansion of macro ‘FLG_ENTRY’
 FLG_ENTRY(GSSAPI_DELEGATION_NONE          )
 ^
src/lcurl.c:173:28: error: ‘CURLGSSAPI_DELEGATION_POLICY_FLAG’ undeclared here (not in a function)
 #define FLG_ENTRY(N) { #N, CURL##N },
                            ^
src/lcflags.h:49:1: note: in expansion of macro ‘FLG_ENTRY’
 FLG_ENTRY(GSSAPI_DELEGATION_POLICY_FLAG   )
 ^
src/lcurl.c:173:28: error: ‘CURLGSSAPI_DELEGATION_FLAG’ undeclared here (not in a function)
 #define FLG_ENTRY(N) { #N, CURL##N },
                            ^
src/lcflags.h:50:1: note: in expansion of macro ‘FLG_ENTRY’
 FLG_ENTRY(GSSAPI_DELEGATION_FLAG          )
 ^

Error: Build error: Failed compiling object src/lcurl.o

sp@ubuntu1040lts:~/luarocks/bin$ dpkg -l | grep curl
ii  curl                                7.19.7-1ubuntu1.11                  Get a file from an HTTP, HTTPS or FTP server
ii  gnupg-curl                          1.4.10-2ubuntu1.8                   GNU privacy guard - a free PGP replacement (
ii  libcurl3                            7.19.7-1ubuntu1.11                  Multi-protocol file transfer library (OpenSS
ii  libcurl3-gnutls                     7.19.7-1ubuntu1.11                  Multi-protocol file transfer library (GnuTLS
ii  libcurl4-openssl-dev                7.19.7-1ubuntu1.11                  Development files and documentation for libc
ii  python-pycurl                       7.19.0-3                            Python bindings to libcurl
```

**Comment by moteus** [comment]
Oldest version with I test is 7.22 (which one installed on Travis)
According [Symbols In Versions](http://curl.haxx.se/libcurl/c/symbols-in-versions.html) CURLGSSAPI_ exists since 7.22.
So may be it sufficient just wrap this options to ifdefs based on version or flags ([lcflags.h](https://github.com/Lua-cURL/Lua-cURLv3/blob/88c610264395fe3e38b7b7cbeb94db526278c571/src/lcflags.h#L48-L50))
```C
#ifdef CURLGSSAPI_DELEGATION_NONE
FLG_ENTRY(GSSAPI_DELEGATION_NONE          )
FLG_ENTRY(GSSAPI_DELEGATION_POLICY_FLAG   )
FLG_ENTRY(GSSAPI_DELEGATION_FLAG          )
#endif
```
I can not test it. So I would appreciate if you can confirm that it works (or better make PR)

**Comment by stepelu** [comment]
Yes I confirm this fixes the issue, the module compile just fine with this change (I messed up the PR on my side, I would appreciate if you could commit the change instead).

Thank you

**Comment by stepelu** [comment]
On a side note, is there a plan to release a new minor version soon (with this fix) ?
